### ISSUE TITLE
peeringdb sync’ won’t work w/ Django==1.9

### ISSUE THREAD

**Issue by grizz** [peeringdb/peeringdb-py#14]

**Comment by grrrrreg** [comment]
Last version in 1.8 trunk of Django did the trick:
`pip install -I Django==1.8.17`

I think it has to do w/ 1.9 deprecating get_app() or something.
Where you used to be able to do:
```
for model in get_model(get_app('myapp')):
     admin.site.register(model)
```

Now you must do:
```
from django.apps import apps

myapp = apps.get_app_config('myapp')
for model in myapp.get_models():
    admin.site.register(model)
```

**Comment by grizz** [comment]
This was fixed last release.
