### ISSUE TITLE
Instructions - more clarity for quick start

### ISSUE THREAD

**Issue by brian-peter-dickson** [peeringdb/peeringdb-py#19]
I got stuck while doing the quick install...

Please emphasis the necessity of doing this, for creating the DB itself, rather than it being a UTF issue:

CREATE DATABASE peeringdb DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;

before trying to do a sync.

(Also, a pointer to any mysql primer for doing mysql from scratch for newbies, would be nice.)

Brian

**Comment by arnoldnipper** [comment]
@peeringdb/20c please take care

**Comment by leovegoda** [comment]
Addressed some time ago and documented in https://docs.peeringdb.com/howto/peeringdb-py/
