### ISSUE TITLE
peeringdb settings not passed through to django_peeringdb using "sync"

### ISSUE THREAD

**Issue by mngan** [peeringdb/peeringdb-py#2]
I noticed that the peeringdb settings in the config.yaml are never passed through the django_peeringdb, so all of your API calls are done using anonymous auth. 

At a minimum, these settings should be configured in localdb to make peeringdb sync work correctly. 

PEERINGDB_SYNC_USERNAME
PEERINGDB_SYNC_PASSWORD
PEERINGDB_SYNC_URL

**Comment by grizz** [comment]
Fixed c3665ca
