### ISSUE TITLE
JSON support broken?

### ISSUE THREAD

**Issue by michela** [peeringdb/peeringdb-py#24]
Python 2.7.13

```
(peeringdb) www-data@datafarms-dev:/srv/env/peeringdb$ peeringdb -O json get net1
Usage: peeringdb [OPTIONS] COMMAND [ARGS]...
Try "peeringdb --help" for help.

Error: no such option: -O
```

**Comment by vegu** [comment]
current client doesnt support a shorthand `-O` flag, it needs to be `--output-format`

also it's a flag specific to the `get` command so needs to be appended after

`peeringdb get net1 --output-format json`
