### ISSUE TITLE
Error while trying to install peeringdb using Python 2.7

### ISSUE THREAD

**Issue by vgiotsas** [peeringdb/peeringdb-py#26]
I try to install `peeringdb-py` version 0.6.1 using pip 9.0.1 for python 2.7

The installation breaks with error:

```
File "/usr/lib/python2.7/distutils/command/build_py.py", line 334, in build_module
        "'package' must be a string (dot-separated), list, or tuple")
    TypeError: 'package' must be a string (dot-separated), list, or tuple
 
    ----------------------------------------
Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-ZGnyfA/twentyc.rpc/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-c5Xuds-record/install-record.txt --single-version-externally-managed --compile --user --prefix=" failed with error code 1 in /tmp/pip-build-ZGnyfA/twentyc.rpc
```

I have the full pip error trace here:
https://pastebin.com/34ut1XDb

My OS is Ubuntu 16.04.3 LTS (xenial)

**Comment by vgiotsas** [comment]
It appears that `twentyc.rpc 0.4.0` is the culprit. 
By installing version 0.3.5 with `pip install twentyc.rpc==0.3.5` before the installation of `peeringdb`, I was able to install and use `peeringdb` successfully. Maybe it would be good to update your installation requirements to < 0.4.0 for `twentyc.rpc`, until at least they resolve the issue.

**Comment by arnoldnipper** [comment]
@peeringdb/20c could you please take care

**Comment by grizz** [comment]
Catching up on issues, python 2 is no longer supported :)
