### ISSUE TITLE
Confu not found

### ISSUE THREAD

**Issue by baerbock** [peeringdb/peeringdb-py#28]
I've installed https://github.com/20c/confu from AUR.

Nevertheless peeringdb complains about missing cfu:

`pkg_resources.DistributionNotFound: The 'cfu>=0.5.1' distribution was not found and is required by peeringdb`

**Comment by arnoldnipper** [comment]
@peeringdb/20c could you please take care

**Comment by grizz** [comment]
Would have been fixed last release, sorry for the delay.
