### ISSUE TITLE
Allow option for logging to co-exist with existing loggers

### ISSUE THREAD

**Issue by jhay317** [peeringdb/peeringdb-py#67]
Currently in the __init__.py a reset is performed for all loggers that exist.   This can cause issues when this is integrated into other applications where logging is utilized.   Two options on how this can be resolved are either an addition to the configuration file to allow_other_loggers: True or to expose the logger that exists within the PeeringDB API to be added to existing loggers.   This is pretty common with other libraries.

**Comment by martinhannigan** [comment]
+1

**Comment by floatingstatic** [comment]
Just ran into this. +1 for fixing
