### ISSUE TITLE
docs need updating to reflect some api changes to the Client.update_all() call

### ISSUE THREAD

**Issue by vegu** [peeringdb/peeringdb-py#88]
https://github.com/peeringdb/peeringdb-py/blob/master/docs/api.md refers to update_all() which was lost during the refactoring in version 2.0.0.

It is now located at `Client.updater.update_all` - this feels like an oversight and we should probably still have it abstracted at `Client.update_all` - at the very least documentation needs updating.

Also double check we're not missing any other changes.

**Comment by jackcarrozzo** [comment]
+1

**Comment by grizz** [comment]
+1

**Comment by arnoldnipper** [comment]
+1
