### ISSUE TITLE
Make client more robust when dealing with api errors.

### ISSUE THREAD

**Issue by vegu** [peeringdb/peeringdb-py#95]
While the ultimate goal is to keep the api error free, this is an ongoing process, and currently in the case where there are data validation errors the client just crashes during sync until someone intervenes and fixes the erroneous data.

It'd be nice if the client could skip the broken objects and retry later when they are fixed, instead of completely breaking down.

**Comment by ccaputo** [comment]
+1

**Comment by mcmanuss8** [comment]
+1

**Comment by jackcarrozzo** [comment]
+1

**Comment by arnoldnipper** [comment]
+1
